# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"func": "index.ipynb",
         "func2": "index.ipynb",
         "func3": "index.ipynb",
         "nothing": "module1.ipynb",
         "nothing_again": "module2.ipynb"}

modules = ["default_module.py",
           "module1.py",
           "module2.py"]

doc_url = "https://hamelsmu.github.io/nbdev_template/"

git_url = "https://github.com/hamelsmu/nbdev_template/tree/master/"

def custom_doc_links(name): return None
