# AUTOGENERATED! DO NOT EDIT! File to edit: module2.ipynb (unless otherwise specified).

__all__ = ['func3', 'nothing_again']

# Comes from index.ipynb, cell
def func3(): pass

# Cell
def nothing_again(): pass