# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"func": "demo.ipynb",
         "func2": "demo.ipynb",
         "func3": "demo.ipynb",
         "nothing": "module1.ipynb",
         "nothing_again": "module2.ipynb"}

modules = ["demo.py",
           "module1.py",
           "module2.py"]

doc_url = "https://hamelsmu.github.io/nbdev_export_demo/"

git_url = "https://github.com/hamelsmu/nbdev_export_demo/tree/master/"

def custom_doc_links(name): return None
